name: alfred_workflow
description: A helper library in Dart for authors of workflows for Alfred.
version: 1.1.5
repository: https://github.com/techouse/alfred_workflow
homepage: https://techouse.github.io/alfred_workflow/
documentation: https://pub.dev/documentation/alfred_workflow/latest/

platforms:
  macos:

environment:
  sdk: ^3.9.0

dependencies:
  equatable_annotations: ^1.2.0
  collection: ^1.19.1
  copy_with_extension: ^10.0.1
  crypto: ^3.0.6
  equatable: ^2.0.7
  file: ^7.0.1
  http: ^1.5.0
  json_annotation: ^4.9.0
  meta: ^1.17.0
  path: ^1.9.1
  plist_parser: ^0.2.5
  pub_semver: ^2.2.0
  stash: ^5.2.0
  stash_file: ^5.2.0

dev_dependencies:
  equatable_gen: ^1.2.0
  build_runner: ^2.9.0
  build_verify: ^3.1.1
  copy_with_extension_gen: ^10.0.1
  faker: ^2.2.0
  json_serializable: ^6.11.1
  lints: ^6.0.0
  mockito: ^5.5.1
  test: ^1.26.3
  data_fixture_dart: ^3.0.0

topics:
  - alfred
  - macos
